### ISSUE TITLE
Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by fissible** [illl48/RobInDaHood#2]
```
RobInDaHood (master) $ npm install

> robindahood@0.0.1 postinstall /Users/allen/scripts/RobInDaHood
> install-app-deps

/Users/allen/scripts/RobInDaHood/node_modules/electron-builder/out/cli/install-app-deps.js:16
let main = (() => {
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! robindahood@0.0.1 postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robindahood@0.0.1 postinstall script 'install-app-deps'.
npm ERR! This is most likely a problem with the robindahood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get their info via:
npm ERR!     npm owner ls robindahood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/allen/scripts/RobInDaHood/npm-debug.log
```

**Comment by perfectra1n** [comment]
My node version states v7.9.0 and my npm version is 4.2.0.
Is yours up to date?

**Comment by fissible** [comment]
Installing Node version 7.9.0 fixed this for me.
